---
title: "ST558 R Project II"
author: "Mana Azizsoltani"
date: "October 16, 2020"
output: rmarkdown::github_document
---

```{r setup, include=FALSE, message=FALSE}
# Set seed for reproducibility
set.seed(445)

# Load necessary libraries
library(knitr)
library(caret)
library(tidyverse)
library(class)
library(randomForest)
library(gbm)
library(corrplot)
library(klaR)
library(Rdimtools)
```

# Introduction

# Data
```{r, message=FALSE}
# Read in data set
dat <- read_csv("OnlineNewsPopularity.csv")
```

# Modeling

```{r}
vars <- c(7, 14, 16:19, 25:27, 36:41, 43:45, 49, 56, 61)
index <- createDataPartition(dat$shares, p = .7, list = F) %>% as.vector()
train <- dat[index,vars]
test <- dat[-index,vars]

# Specify CV method
trctrl <- trainControl(method = "cv", number = 5)

# Fit Random Forest
treeFit <- train(shares ~., data = train, method = "rpart",
                 trControl=trctrl, preProcess = c("center", "scale"))

rf <- train(shares ~., data = train, method = "rf",
            trControl=trctrl, preProcess = c("center", "scale"),
            verbose = FALSE, importance = TRUE)
rfPred <- predict(rf, newdata = test)
rfRMSE <- sqrt(mean((rfPred-test$shares)^2))
rf

treebagFit <- train(shares ~., data = train, method = "treebag",
                    trControl=trctrl, preProcess = c("center", "scale"))

boostFit <- train(shares ~., data = train, method = "gbm",
                  trControl = trctrl, preProcess = c("center", "scale"),
                  verbose = FALSE, tuneGrid = gbmGrid)

```

